version: '3'
services:
  postgres_db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    container_name: forecast-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=forecast
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: forecast-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - data:/data

volumes:
  data:
    name:
      "data"
