# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-01-28T10:57:34+00:00

from __future__ import annotations

from pydantic import BaseModel


class Weather(BaseModel):
    code: int
    icon: str
    description: str


class Datum(BaseModel):
    app_temp: float
    azimuth: float
    clouds: int
    datetime: str
    dewpt: float
    dhi: int
    dni: int
    elev_angle: float
    ghi: int
    h_angle: None
    pod: str
    precip: float
    pres: int
    revision_status: str
    rh: int
    slp: int
    snow: int
    solar_rad: int
    temp: float
    timestamp_local: str
    timestamp_utc: str
    ts: int
    uv: float
    vis: int
    weather: Weather
    wind_dir: int
    wind_gust_spd: float
    wind_spd: float


class WeatherBitSchema(BaseModel):
    city_id: str
    city_name: str
    country_code: str
    data: list[Datum]
    lat: float
    lon: float
    sources: list[str]
    state_code: str
    station_id: str
    timezone: str
