# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-01-28T10:57:34+00:00

from __future__ import annotations

from pydantic import BaseModel


class VisualCrossingSchema(BaseModel):
    cod: int
    message: str
