"""empty message

Revision ID: 2c38b9fb6fbf
Revises: ed26c75307b8
Create Date: 2024-02-02 14:18:45.809271

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2c38b9fb6fbf'
down_revision: Union[str, None] = 'ed26c75307b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_name'), table_name='city')
    # ### end Alembic commands ###
