"""empty message

Revision ID: 32e339f8fc54
Revises: 541bec285a55
Create Date: 2024-01-31 19:32:48.416191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32e339f8fc54'
down_revision: Union[str, None] = '541bec285a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('apparent_temperature', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('wind_gust_speed', sa.Float(), nullable=False),
    sa.Column('wind_direction', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('clouds', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=False),
    sa.Column('snow', sa.Float(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hitstorical_hourly_weather')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hitstorical_hourly_weather',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('apparent_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pressure', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('wind_gust_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('wind_direction', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('humidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('clouds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('precipitation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('snow', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name='hitstorical_hourly_weather_city_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='hitstorical_hourly_weather_pkey')
    )
    op.drop_table('weather_journal')
    # ### end Alembic commands ###
