"""whatever

Revision ID: 33ef507f9872
Revises:
Create Date: 2024-02-02 20:03:13.534675

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33ef507f9872'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'city',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('country_name', sa.String(), nullable=False),
        sa.Column('population', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_city_name'), 'city', ['name'], unique=False)
    op.create_table(
        'weather_journal',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('data_source', sa.String(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('pressure', sa.Float(), nullable=True),
        sa.Column('wind_speed', sa.Float(), nullable=True),
        sa.Column('wind_direction', sa.Float(), nullable=True),
        sa.Column('humidity', sa.Float(), nullable=True),
        sa.Column('clouds', sa.Float(), nullable=True),
        sa.Column('precipitation', sa.Float(), nullable=True),
        sa.Column('snow', sa.Float(), nullable=True),
        sa.Column('city_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['city_id'],
            ['city.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_weather_journal_date'), 'weather_journal', ['date'], unique=False
    )
    op.create_index(
        op.f('ix_weather_journal_precipitation'),
        'weather_journal',
        ['precipitation'],
        unique=False,
    )
    op.create_index(
        op.f('ix_weather_journal_temperature'),
        'weather_journal',
        ['temperature'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_journal_temperature'), table_name='weather_journal')
    op.drop_index(
        op.f('ix_weather_journal_precipitation'), table_name='weather_journal'
    )
    op.drop_index(op.f('ix_weather_journal_date'), table_name='weather_journal')
    op.drop_table('weather_journal')
    op.drop_index(op.f('ix_city_name'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
