"""Made ascii name not unique + source list id

Revision ID: 44ecff040ed6
Revises: e3a5b4c20f5e
Create Date: 2024-01-29 20:29:29.035347

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44ecff040ed6'
down_revision: Union[str, None] = 'e3a5b4c20f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('source_list_id', sa.Integer(), nullable=False))
    op.drop_constraint('city_name_ascii_key', 'city', type_='unique')
    op.create_unique_constraint(None, 'city', ['source_list_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    op.create_unique_constraint('city_name_ascii_key', 'city', ['name_ascii'])
    op.drop_column('city', 'source_list_id')
    # ### end Alembic commands ###
