"""Initial

Revision ID: 8a7265a1b493
Revises:
Create Date: 2024-01-28 00:55:46.370703

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '8a7265a1b493'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
