"""Added basic data structure

Revision ID: 8ac30a6ef6e5
Revises: 8a7265a1b493
Create Date: 2024-01-29 20:04:50.957913

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8ac30a6ef6e5'
down_revision: Union[str, None] = '8a7265a1b493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'city',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('name_ascii', sa.String(), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('country_name', sa.String(), nullable=False),
        sa.Column('iso_code_two', sa.String(), nullable=False),
        sa.Column('iso_code_three', sa.String(), nullable=False),
        sa.Column('population', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'location',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('latidute', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('city_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['city_id'],
            ['city.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'hitstorical_hourly_weather',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('pressure', sa.Float(), nullable=False),
        sa.Column('wind_speed', sa.Float(), nullable=False),
        sa.Column('wind_gust_speed', sa.Float(), nullable=False),
        sa.Column('wind_dir', sa.Float(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=False),
        sa.Column('feelslike_temp', sa.Float(), nullable=False),
        sa.Column('humidity', sa.Float(), nullable=False),
        sa.Column('clouds', sa.Float(), nullable=False),
        sa.Column('visibility', sa.Float(), nullable=False),
        sa.Column('precipitation', sa.Float(), nullable=False),
        sa.Column('snow', sa.Float(), nullable=False),
        sa.Column('location_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['location_id'],
            ['location.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hitstorical_hourly_weather')
    op.drop_table('location')
    op.drop_table('city')
    # ### end Alembic commands ###
