"""added indecies

Revision ID: 9e1f77256db5
Revises: 67d1b70e398f
Create Date: 2024-02-02 00:19:50.864061

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e1f77256db5'
down_revision: Union[str, None] = '67d1b70e398f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_journal_date', table_name='weather_journal')
    op.drop_index('idx_weather_journal_precipitation', table_name='weather_journal')
    op.drop_index('idx_weather_journal_temperature', table_name='weather_journal')
    op.create_index(
        op.f('ix_weather_journal_date'), 'weather_journal', ['date'], unique=False
    )
    op.create_index(
        op.f('ix_weather_journal_precipitation'),
        'weather_journal',
        ['precipitation'],
        unique=False,
    )
    op.create_index(
        op.f('ix_weather_journal_temperature'),
        'weather_journal',
        ['temperature'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_journal_temperature'), table_name='weather_journal')
    op.drop_index(
        op.f('ix_weather_journal_precipitation'), table_name='weather_journal'
    )
    op.drop_index(op.f('ix_weather_journal_date'), table_name='weather_journal')
    op.create_index(
        'idx_weather_journal_temperature',
        'weather_journal',
        ['temperature'],
        unique=False,
    )
    op.create_index(
        'idx_weather_journal_precipitation',
        'weather_journal',
        ['precipitation'],
        unique=False,
    )
    op.create_index(
        'idx_weather_journal_date', 'weather_journal', ['date'], unique=False
    )
    # ### end Alembic commands ###
