"""empty message

Revision ID: acf4bdd9fdb3
Revises: b4aa93353c66
Create Date: 2024-02-01 21:06:17.449439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf4bdd9fdb3'
down_revision: Union[str, None] = 'b4aa93353c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_source_list_id_key', 'city', type_='unique')
    op.drop_column('city', 'source_list_id')
    op.drop_column('city', 'iso_code_three')
    op.drop_column('city', 'iso_code_two')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('iso_code_two', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('city', sa.Column('iso_code_three', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('city', sa.Column('source_list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('city_source_list_id_key', 'city', ['source_list_id'])
    # ### end Alembic commands ###
