"""Remove unique from name_ascii

Revision ID: d544d439b854
Revises: 44ecff040ed6
Create Date: 2024-01-29 20:32:39.023634

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd544d439b854'
down_revision: Union[str, None] = '44ecff040ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('city_name_key', 'city', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('city_name_key', 'city', ['name'])
    # ### end Alembic commands ###
