"""Make city name unique

Revision ID: e3a5b4c20f5e
Revises: 8ac30a6ef6e5
Create Date: 2024-01-29 20:14:03.662765

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3a5b4c20f5e'
down_revision: Union[str, None] = '8ac30a6ef6e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'city', ['name'])
    op.create_unique_constraint(None, 'city', ['name_ascii'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    # ### end Alembic commands ###
