"""empty message

Revision ID: eda12587c820
Revises: 32e339f8fc54
Create Date: 2024-02-01 19:38:16.092089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda12587c820'
down_revision: Union[str, None] = '32e339f8fc54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_journal', 'apparent_temperature')
    op.drop_column('weather_journal', 'wind_gust_speed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_journal', sa.Column('wind_gust_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('weather_journal', sa.Column('apparent_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
