# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-01-29T09:11:47+00:00

from __future__ import annotations

from pydantic import BaseModel


class HourlyUnits(BaseModel):
    time: str
    temperature_2m: str
    relative_humidity_2m: str
    apparent_temperature: str
    precipitation: str
    rain: str
    snowfall: str
    snow_depth: str
    surface_pressure: str
    cloud_cover: str
    wind_speed_10m: str
    wind_speed_100m: str
    wind_direction_10m: str
    wind_direction_100m: str
    wind_gusts_10m: str


class Hourly(BaseModel):
    time: list[str]
    temperature_2m: list[float]
    relative_humidity_2m: list[int]
    apparent_temperature: list[float]
    precipitation: list[float]
    rain: list[float]
    snowfall: list[float]
    snow_depth: list[float]
    surface_pressure: list[float]
    cloud_cover: list[int]
    wind_speed_10m: list[float]
    wind_speed_100m: list[float]
    wind_direction_10m: list[int]
    wind_direction_100m: list[int]
    wind_gusts_10m: list[float]


class OpenWeatherMapSchema(BaseModel):
    latitude: float
    longitude: float
    generationtime_ms: float
    utc_offset_seconds: int
    timezone: str
    timezone_abbreviation: str
    elevation: float
    hourly_units: HourlyUnits
    hourly: Hourly
