# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2024-01-28T17:59:06+00:00

from __future__ import annotations

from pydantic import BaseModel


class RequestItem(BaseModel):
    type: str
    query: str


class AstronomyItem(BaseModel):
    sunrise: str
    sunset: str
    moonrise: str
    moonset: str
    moon_phase: str
    moon_illumination: str


class WeatherIconUrlItem(BaseModel):
    value: str


class WeatherDescItem(BaseModel):
    value: str


class HourlyItem(BaseModel):
    time: str
    tempC: str
    tempF: str
    windspeedMiles: str
    windspeedKmph: str
    winddirDegree: str
    winddir16Point: str
    weatherCode: str
    weatherIconUrl: list[WeatherIconUrlItem]
    weatherDesc: list[WeatherDescItem]
    precipMM: str
    precipInches: str
    humidity: str
    visibility: str
    visibilityMiles: str
    pressure: str
    pressureInches: str
    cloudcover: str
    HeatIndexC: str
    HeatIndexF: str
    DewPointC: str
    DewPointF: str
    WindChillC: str
    WindChillF: str
    WindGustMiles: str
    WindGustKmph: str
    FeelsLikeC: str
    FeelsLikeF: str
    uvIndex: str


class WeatherItem(BaseModel):
    date: str
    astronomy: list[AstronomyItem]
    maxtempC: str
    maxtempF: str
    mintempC: str
    mintempF: str
    avgtempC: str
    avgtempF: str
    totalSnow_cm: str
    sunHour: str
    uvIndex: str
    hourly: list[HourlyItem]


class Data(BaseModel):
    request: list[RequestItem]
    weather: list[WeatherItem]


class OpenWeatherMapSchema(BaseModel):
    data: Data
