data_sources:
  weatherbit:
    api_key: "your_api_key"
  open_weather_map:
    api_key: "your_api_key"
  visual_crossing:
    api_key: "your_api_key"
db:
  connection_string: "your_postgres_connection_string"
